apiVersion: v1
kind: ReplicationController
metadata: 
  name: webapp1
spec:
  replicas: 2
  template: 
    metadata:
      name: webapp1
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: tomcat
        ports:
        - containerPort: 8080
